services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: 'TheBoss123?com'
      DNSMASQ_LISTENING: 'all'
      DNS_FQDN_REQUIRED: 'true'
      DNS_BOGUS_PRIV: 'true'
      DNSSEC: 'true'
      ServerIP: '192.168.1.133'
      DNS1: '127.0.0.1#5335'
      DNS2: '127.0.0.1#5335'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8000:80/tcp"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    volumes:
      - './unbound:/opt/unbound/etc/unbound'
    restart: unless-stopped
